id: DCE16EFB3
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2021-12-31T06:58:21+00:00'
last_modified: '2022-05-30T04:12:51.158052+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/a7eec5e12ddce18d0ed1dbb732a42cf48f94dd09/openpecha/formatters/hfml.py
source_metadata:
  base:
    9e54:
      image_group_id: I1PD95939
      title: སྐྱེས་པའི་རབས་ཀྱི་རྒྱ་ཆེར་བཤད་པ།
      total_pages: 1645
      order: 94
      base_file: 9e54.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
