id: P4F9039CC
initial_creation_type: ocr
source_metadata:
  volumes:
    b4bec20027224ca3a513f8026dcc5afe:
      base_file: v094.txt
      image_group_id: I1PD95939
      title: སྐྱེས་པའི་རབས་ཀྱི་རྒྱ་ཆེར་བཤད་པ།
      total_pages: 1645
      volume_number: 94
